### ISSUE TITLE
Remove old website

### ISSUE THREAD

**Issue by jnwarp** [CyberLions/CyberLions.github.io#5]
Currently the [old CCSO website](https://sites.psu.edu/ccso/) is the top search result on Google. We should probably take down the old site as we are transitioning to this new website.

![screen shot 2017-05-07 at 12 14 26 pm](https://cloud.githubusercontent.com/assets/15384122/25782782/e1888bac-331e-11e7-95ca-577a32a6a032.png)

**Comment by Amar1729** [comment]
Maybe we could just have the page redirect (http 403?)

**Comment by jnwarp** [comment]
Added an HTTP redirect from the old site:
```
<meta http-equiv="refresh" 
   content="0; url=https://cyberlions.github.io/">
```
