### ISSUE TITLE
Update the link on Penn State's official website

### ISSUE THREAD

**Issue by jnwarp** [CyberLions/CyberLions.github.io#6]
[Penn State's official website](https://ist.psu.edu/students/engagement/clubs_orgs/ccso) still points to the old URL, we should probably fix that. 

![screen shot 2017-05-07 at 12 18 14 pm](https://cloud.githubusercontent.com/assets/15384122/25782793/45efab5c-331f-11e7-8203-ccab50b5d292.png)

**Comment by KMHouk** [comment]
I'll take care of it

**Comment by KMHouk** [comment]
Fixed!
